# Generated by Django 2.2.5 on 2019-10-26 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_follow', models.DateTimeField(auto_now_add=True)),
                ('follow_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_who_set', to=settings.AUTH_USER_MODEL)),
                ('who_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_follow_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(through='user.Follow_Detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
