# Generated by Django 2.2.5 on 2019-10-26 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191026_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hate_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hate', models.DateTimeField(auto_now_add=True)),
                ('hate_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hate_who_set', to=settings.AUTH_USER_MODEL)),
                ('who_hate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_hate_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='hate',
            field=models.ManyToManyField(related_name='hate_set', through='user.Hate_Detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
