# Generated by Django 2.2.5 on 2019-10-26 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191026_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_relation', models.DateTimeField(auto_now_add=True)),
                ('relation_type', models.IntegerField(choices=[(0, '无关'), (-1, '拉黑'), (1, '关注'), (2, '不再推荐')])),
            ],
        ),
        migrations.RemoveField(
            model_name='hate_detail',
            name='hate_who',
        ),
        migrations.RemoveField(
            model_name='hate_detail',
            name='who_hate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hate',
        ),
        migrations.DeleteModel(
            name='Follow_Detail',
        ),
        migrations.DeleteModel(
            name='Hate_Detail',
        ),
        migrations.AddField(
            model_name='relation_detail',
            name='relation_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_who_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relation_detail',
            name='who_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_relation_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='relation',
            field=models.ManyToManyField(through='user.Relation_Detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
