# Generated by Django 2.2.5 on 2019-10-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191026_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_detail',
            name='relation_type',
            field=models.IntegerField(choices=[(0, '无关'), (-1, '拉黑'), (1, '关注'), (2, '不再推荐')], default=0),
        ),
    ]
