# Generated by Django 2.2.5 on 2019-10-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191026_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_detail',
            name='relation_type',
            field=models.IntegerField(default=0),
        ),
    ]
