# Generated by Django 2.2.5 on 2019-10-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191026_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='text',
        ),
    ]
