# Generated by Django 2.2.5 on 2019-10-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20191026_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
