# Generated by Django 2.2.5 on 2019-10-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articlecategory_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_great',
            field=models.BooleanField(default=0),
        ),
    ]
