# Generated by Django 2.2.5 on 2019-10-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_is_great'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_great',
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='is_great',
            field=models.BooleanField(default=0),
        ),
    ]
