# Generated by Django 2.2.5 on 2019-10-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_is_great'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commenr_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
