# Generated by Django 2.2.5 on 2019-10-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20191027_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='commenr_count',
            new_name='comment_count',
        ),
    ]
