# Generated by Django 2.2.5 on 2019-11-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20191027_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='hot_Info_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('article_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'hot_view',
            },
        ),
    ]
