# Generated by Django 2.2.5 on 2019-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20191104_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_user',
            field=models.IntegerField(null=True),
        ),
    ]
